(define (sqrt-newton x)
    (define (square num) (* num num)) 
    (define (abs num) (if (< num 0) (- num) num)) 
    (define (average num1 num2) (/ (+ num1 num2) 2)) 
    (define (enough? guess)
         (< (abs (- (square guess) x)) 0.001)) 
    (define (improve guess) (average guess (/ x guess))) 
    (define (approx guess)
	 (if (enough? guess)
	      guess
	      (approx (improve guess)))) 
    (approx 1.0))
